name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npx npm-version-git
        env:
          GIT_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Build the package
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version bump
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push origin HEAD:main --follow-tags
